# Credenciais da NIC-LABS
# RECOMENDAÇÃO: Criptografe este arquivo com 'ansible-vault encrypt vars/secrets.yml'

# 1. Conectividade (Cloudflare Tunnel)
# Obtenha este token no painel Zero Trust > Access > Tunnels
cloudflare_tunnel_token: "eyJhIjoi..."

# 2. Banco de Dados (PostgreSQL e NocoDB)
db_user: "nic_admin"
db_password: "SuaSenhaForte2025!"