---
- name: Instalar dependências do Docker
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Criar diretório para chave GPG
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Adicionar chave GPG oficial do Docker
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true

- name: Adicionar repositorio oficial Docker
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu noble stable"
    state: present

- name: Instalar Docker Engine e Compose
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Adicionar usuário 'nic-core' ao grupo Docker
  user:
    name: nic-core
    groups: docker
    append: yes